[required]
git
gh
ksshaskpass
7zip
rclone
crudini
snapper
grub-btrfs
rsync

[daily-driver]
vlc
okular
libreoffice-writer
libreoffice-calc
libreoffice-impress
libreoffice-draw
steam
kde-partitionmanager
switcheroo-control
htop
nvidia-smi
nvtop


[daily-driver-flatpak]
eu.betterbird.Betterbird

[development]
code

[development-flatpak]
io.dbeaver.DBeaverCommunity
com.mongodb.Compass

[uninstall]
kmines
kpat
kmahjongg
kajongg
ksudoku
kreversi
kbounce
granatier
bovo
palapeli
korganizer
kontact
kmail
kmail-import-wizard
akregator
kaddressbook
ktnef
kmouth
skanpage
khelpcenter
krdc
krfb
neochat
pim-sieve-editor
orca
kleopatra
kolourpaint
dragon
elisa-player
filelight
plasma-vault
plasma-workspace-wallpapers
fedora-bookmarks
virtualbox-guest-additions
open-vm-tools-desktop
anaconda-live
kdeconnectd



