# restore.conf — Single source of truth for configuration files to backup and restore
[home]
.gitconfig
.ssh/config
.config/powerdevilrc
.config/Code/User/settings.json
.config/Code/User/keybindings.json
.config/Code/snippets/
.local/bin/ssh-autostart.sh

[system]
dnf/dnf.conf
snapper/configs/root
default/grub
