[home]
.ssh/config
.config/powerdevilrc
.config/Code/User/settings.json
.config/Code/User/keybindings.json
.config/Code/User/snippets/
.config/autostart/
.config/systemd/user/
.config/baloofilerc
.config/mozilla/firefox/profiles.ini
.config/mozilla/firefox/main-profile/user.js
.config/mozilla/firefox/main-profile/chrome/


[system]
dnf/dnf.conf
snapper/configs/root
default/grub
sysctl.d/90-inotify.conf



[keys]
.config/rclone/rclone.conf
.gitconfig
.ssh
