# WARNING: This file is intentionally mirrored with backup-list.conf and must be updated together.
[home]
.gitconfig
.ssh/config
.config/powerdevilrc

[system]
dnf/dnf.conf
snapper/configs/root
default/grub
